name: msfatigue
description: 'Collect surveys to review fatigue associated with MS.'
publish_to: 'none'
version: 1.1.0+9

environment:
  sdk: ">=3.2.3 <4.0.0"

# To automatically upgrade package dependencies to the latest versions:
#
#   flutter pub upgrade --major-versions
#
# To see which dependencies have newer versions available:
#
#   flutter pub outdated

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  flutter_markdown: ^0.7.6+2
  gap: ^3.0.1
  intl: any
  markdown_tooltip: ^0.0.6
  package_info_plus: ^8.2.1
  rdflib: ^0.2.11
  shared_preferences: ^2.5.2
  solidpod: ^0.7.10
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2

dependency_overrides:
  collection: ^1.19.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/markdown/fatigue_small_questionnaire.md
    - assets/markdown/participant.md

# Define launcher icons for all platforms (except Linux) so icons for
# the apps can be automatically updated using:
#
# `dart run flutter_launcher_icons`
#
# (gjw 20250429)

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  macos:
    generate: true
  web:
    generate: true
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
