name: msfatigue
description: 'Collect surveys to review fatigue with MS.'
publish_to: 'none'
version: 0.0.5+3

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.6
  gap: ^3.0.1
  rename_app: ^1.6.2
  solidpod:
    git:
      url: https://github.com/anusii/solidpod
      ref: dc/254_refactor_parseTTL
  window_manager: ^0.4.3
  universal_io: ^2.2.2
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  path: ^1.9.0
  rdflib: ^0.2.11
  shared_preferences: ^2.5.2
  shared_preferences_web: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.14
  dart_code_metrics:
    git:
      url: https://github.com/anusii/dart-code-metrics.git
      ref: dev
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3

dependency_overrides:
  #  file: ^7.0.0 # Use only if necessary
  intl: ^0.19.0 # Use only if necessary
  collection: ^1.19.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/markdown/fatigue_questionnaire.md
    - assets/markdown/fatigue_small_questionnaire.md

# Update icons with `dart run flutter_launcher_icons`

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'assets/images/icon.png'
  windows:
    generate: true
    image_path: 'assets/images/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/images/icon.png'
