List<String> questions = [
  "I am feeling fatigued after physical activity.",
  "I am feeling fatigued because of pain.",
  "I am feeling fatigued due to a stressful situation.",
  "I am feeling fatigued due to anxiety and/or depression.",
  "I am feeling fatigued because of work or social interactions.",
  "I am feeling tired because my existing MS symptoms are worse.",
  "I am feeling fatigued due to the side effects of my MS medication.",
  "I am feeling fatigued because I got hot.",
  "I am feeling fatigued because I got cold.",
  "I am feeling more fatigued as the day progresses.",
  "I am feeling fatigued because I have not been eating well or drinking enough.",
  "I am feeling fatigued because of poor sleep.",
  "I am feeling fatigued because I have not been mobile or physically active.",
  "I feel like I have no energy to do anything even reading or thinking.",
  "I am having more difficulty than usual using specific muscles.",
  "I am feeling clumsier and more uncoordinated than usual.",
  "I am having more trouble than usual maintaining physical effort.",
  "My muscles feel weaker than usual.",
  "I am feeling less alert than usual.",
  "I am finding it hard to concentrate or think clearly.",
  "I am feeling forgetful.",
  "I am feeling irritable and easily angered.",
  "I am finding it difficult to deal with my emotions.",
  "I am feeling unable to provide emotional support to others.",
  "I am feeling too fatigued to participate in social activities.",
  "Because of my fatigue, I have to pace or limit my physical activities.",
  "Because of my fatigue, I don’t feel like doing anything that requires physical effort.",
  "Because of my fatigue, I need to rest longer and/or more often than usual.",
  "Because of my fatigue, I am unable to complete some tasks that require physical effort.",
  "Because of my fatigue, I am having difficulty paying attention.",
  "Because of my fatigue, I am having trouble finishing tasks that require thinking.",
  "Because of my fatigue, I am having difficulty organising my thoughts.",
  "Because of my fatigue, I am having difficulty finding the words I want to say.",
  "Because of my fatigue, I am finding it difficult to make decisions.",
  "Because of my fatigue, I don’t feel like doing anything that requires thinking.",
  "Because of my fatigue, I am feeling stressed.",
  "Because of my fatigue, minor difficulties seem like major obstacles.",
  "Because of my fatigue, I am avoiding situations that stress me.",
  "Because of my fatigue, I am feeling unmotivated to do anything.",
  "Because of my fatigue, I am finding it hard to carry out tasks effectively (at home and/or at work).",
  "Because of my fatigue, I have to rely on others to help me.",
  "Because of my fatigue, I am having difficulty participating in family/leisure/social activities.",
  "Because of my fatigue, I am having difficulty fulfilling my family/household responsibilities.",
  "Because of my fatigue, I find it hard to travel."
];
